stages:
  - build_and_deploy

build_and_deploy_job:
  stage: build_and_deploy
  tags:
    - ogura-staging
  script:
    - npm install -D
    - npm run build
    - test -d ~/ogura_sample || mkdir ~/ogura_sample
    - cp ./* ~/ogura_sample/
    - cd ${DEST}
    - docker-compose up -d
  cache:
    paths:
      - elm-stuff
      - node_modules
  only:
    - master