stages:
  - build_and_deploy

build_and_deploy_job:
  stage: build_and_deploy
  tags:
    - ogura-staging
  script:
    - npm install -D
    - npm run build
    - test -f ~/ogura_sample/next_live.txt && cp ~/ogura_sample/next_live.txt ./ || touch next_live.txt
    - test -d ~/ogura_sample && rm -rf ~/ogura_sample
    - mkdir ~/ogura_sample
    - cp -R ./* ~/ogura_sample/
    - cd ~/ogura_sample
    - htpasswd -c -b .htpasswd ${AUTH_USER} ${AUTH_PASSWD}
    - docker-compose up -d
  cache:
    paths:
      - elm-stuff
      - node_modules
  only:
    - master