stages:
  - build_and_deploy

build_and_deploy_job:
  image: node:8-jessie
  before_script:
    # see https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which nodejs || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  stage: build_and_deploy
  script:
    - npm install -D
    - npm run build
    - test -f next_live.txt && rm next_live.txt
    - scp ./* ${DEPLOY_USER}@${DEPLOY_ADDRESS}:~/ogura_sample/
  cache:
    paths:
      - elm-stuff
      - node_modules
  only:
    - master