stages:
  - build_and_deploy

build_and_deploy_job:
  stage: build_and_deploy
  tags:
    - ogura-staging
  script:
    - npm install -D
    - npm run build
    - cp ./* ${DEST}/
  cache:
    paths:
      - elm-stuff
      - node_modules
  only:
    - master