version: "2"
services:
    web:
        image: nginx
        volumes:
            - ./:/usr/share/nginx/html
            - ./.htpasswd:/etc/nginx/.htpasswd
            - ./nginx.cnf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        restart: always
    sftp:
        image: atmoz/sftp
        volumes:
           - ./:/home/example/upload
        ports:
             - "2222:22"
        command: example:example:1000
        restart: always

